import os
import sys
import time
import glob
import argparse
import datetime
import random
import itertools
import cv2
import xml.dom.minidom


# Ensure the project root is in the python path to allow absolute imports from src
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.insert(0, project_root)


from src.application import Application


def apply_random_augmentation(pcb_image):
    """
    Applies a random transformation to the PCBImage to simulate variations.
    Possible transformations: Horizontal flip, Vertical flip, Slight rotation, or None.
    """
    pcb_image._calculate_dimensions()
    img = pcb_image._decoded_image

    if img is None:
        return

    choice = random.choice(['hflip', 'vflip', 'rotate', 'none'])

    if choice == 'hflip':
        img = cv2.flip(img, 1)
    elif choice == 'vflip':
        img = cv2.flip(img, 0)
    elif choice == 'rotate':
        angle = random.uniform(-5, 5)
        h, w = img.shape[:2]
        center = (w // 2, h // 2)
        M = cv2.getRotationMatrix2D(center, angle, 1.0)
        img = cv2.warpAffine(img, M, (w, h), borderValue=(0, 0, 0))

    if choice != 'none':
        success, buffer = cv2.imencode('.jpg', img)
        if success:
            pcb_image._image_data = buffer.tobytes()
            pcb_image._decoded_image = img


def print_xml_if_requested(result, print_xml):
    """
    If --print-xml flag is set, prints the XML output of the detector to terminal.
    Looks for 'xml_content' (raw string) or 'xml_path' (file path) in the result dict.
    """
    if not print_xml or not result:
        return

    xml_content = result.get("xml_content")
    xml_path = result.get("xml_path")

    try:
        if xml_content:
            pretty_xml = xml.dom.minidom.parseString(xml_content).toprettyxml(indent="  ")
            print("\n===== XML OUTPUT =====")
            print(pretty_xml)
        elif xml_path and os.path.exists(xml_path):
            with open(xml_path, "r", encoding="utf-8") as f:
                raw_xml = f.read()
            pretty_xml = xml.dom.minidom.parseString(raw_xml).toprettyxml(indent="  ")
            print("\n===== XML OUTPUT =====")
            print(pretty_xml)
        else:
            print("\n[--print-xml] No XML content or xml_path found in result.")
    except Exception as e:
        print(f"[--print-xml] Could not print XML: {e}")


def main():
    """
    Main execution flow for the PCB inspection system.
    Demonstrates how to use the Application API.
    """
    parser = argparse.ArgumentParser(description="PCB Solder Defect Detector")
    parser.add_argument('--mode', type=str, choices=['single', 'simulate'], default='single',
                        help="Execution mode: 'single' for a single image capture, 'simulate' for a continuous simulation.")
    parser.add_argument('--image', type=str, default=None,
                        help="Path to an image file (for 'single' mode). If not provided, it attempts to use the physical camera.")
    parser.add_argument('--sim_time', type=float, default=None,
                        help="Total duration of the simulation in seconds before stopping and generating a report. If not provided, runs indefinitely until Ctrl+C.")
    parser.add_argument('--mean', type=float, default=0.0,
                        help="Mean wait time between plates in seconds for the Gaussian distribution. If 0, it runs at maximum speed.")
    parser.add_argument('--deviation', type=float, default=0.0,
                        help="Standard deviation of the wait time between plates in seconds.")
    parser.add_argument('--print-xml', action='store_true',
                        help="Prints the XML output generated by the detector to terminal after each detection.")
    parser.add_argument('--visualize', action='store_true',
                        help="Enable visualization window showing detections.")
    args = parser.parse_args()


    try:
        system = Application(visualize=args.visualize)
    except Exception as e:
        print(f"Failed to initialize Application: {e}")
        return


    if args.mode == 'single':
        if args.image:
            result = system.process_from_path(args.image)
            print_xml_if_requested(result, args.print_xml)
        else:
            result = system.process_live_camera()
            print_xml_if_requested(result, args.print_xml)

        if args.visualize:
            print("\n[Visualization Enabled] Press any key in the image window to exit...")
            system.wait_for_key()

    elif args.mode == 'simulate':
        simulate_dir = os.path.join(project_root, "data", "simulate")
        print(f"\n--- Entering Simulation Mode ---")
        print(f"Reading base images from: {simulate_dir}")

        if not os.path.exists(simulate_dir):
            print(f"Simulation directory not found: {simulate_dir}")
            return

        valid_extensions = ('*.jpg', '*.jpeg', '*.png')
        image_files = []
        for ext in valid_extensions:
            image_files.extend(glob.glob(os.path.join(simulate_dir, ext)))

        image_files.sort()

        if not image_files:
            print(f"No images found in {simulate_dir}")
            return

        if args.sim_time is not None:
            print(f"Starting {args.sim_time}-second simulation with {len(image_files)} base images.")
        else:
            print(f"Starting indefinite simulation with {len(image_files)} base images. Press Ctrl+C to stop.")

        if args.mean > 0:
            print(f"Gaussian cadence: mean={args.mean}s, deviation={args.deviation}s\n")
        else:
            print("Maximum speed mode (no cadence delay).\n")

        total_images = 0
        overall_start_time = time.time()
        processing_times = []

        try:
            for img_path in itertools.cycle(image_files):
                if args.sim_time is not None:
                    if (time.time() - overall_start_time) >= args.sim_time:
                        print(f"\nSimulation time ({args.sim_time}s) reached.")
                        break

                start_time = time.time()

                print(f"\n[Sim] Processing augmented image from: {img_path}")
                pcb_img = system.camera.get_image_from_file(img_path)
                apply_random_augmentation(pcb_img)

                result = system.process_pcb_image(
                    pcb_img,
                    custom_name=f"{os.path.splitext(os.path.basename(img_path))[0]}_aug"
                )
                print_xml_if_requested(result, args.print_xml)

                proc_time = result.get('processing_time_s', 0.0)
                if proc_time > 0:
                    processing_times.append(proc_time)

                total_images += 1

                elapsed_proc = time.time() - start_time
                if args.mean > 0:
                    target_sleep = random.gauss(args.mean, args.deviation)
                    sleep_time = max(0.1, target_sleep - elapsed_proc)
                    print(f"Waiting for next plate... ({sleep_time:.2f}s)")
                    system.wait(sleep_time)
                else:
                    system.wait(0)

        except KeyboardInterrupt:
            print("\nSimulation aborted by user.")

        print("\nGenerating Simulation Report...")
        if processing_times:
            total_elapsed = time.time() - overall_start_time
            fps = total_images / total_elapsed
            avg_time = sum(processing_times) / len(processing_times)
            max_time = max(processing_times)
            min_time = min(processing_times)

            print("\n--- Simulation Speed Statistics ---")
            print(f"Total images processed: {total_images}")
            print(f"Total time elapsed: {total_elapsed:.2f} seconds")
            print(f"Speed: {fps:.2f} FPS")
            print(f"Average processing time per image: {avg_time*1000:.2f} ms")

            report_dir = os.path.join(project_root, "reports", "simulate")
            os.makedirs(report_dir, exist_ok=True)

            timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
            report_filename = os.path.join(report_dir, f"simulation_report_{timestamp}.txt")

            with open(report_filename, 'w') as f:
                f.write("=== Simulation Mode Report ===\n")
                f.write(f"Timestamp: {timestamp}\n")
                f.write(f"Total Uptime: {total_elapsed:.2f} seconds\n")
                f.write(f"Total Images Processed: {total_images}\n")
                f.write(f"Effective Speed: {fps:.2f} FPS\n")
                f.write(f"Average Processing Time: {avg_time*1000:.2f} ms\n")
                f.write(f"Max Processing Time: {max_time*1000:.2f} ms\n")
                f.write(f"Min Processing Time: {min_time*1000:.2f} ms\n")

            print(f"\nSimulation report saved to: {report_filename}")
        else:
            print("No images were processed. No report generated.")


if __name__ == "__main__":
    main()
